name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
         node-version: '13.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run tests
      run: yarn test

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile  
      - name: Build
        run: scripts/build
       
